### ISSUE TITLE
failed in create encironment

### ISSUE THREAD

**Issue by wintermydream** [Lee-Jun-Hyuk-37/SSRPC#1]
conda env create -f environment.yaml
Channels:
 - defaults
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

**Comment by Lee-Jun-Hyuk-37** [comment]
Thank you for informing me about this error. I deleted the **environment.yaml** file, which was causing the problem. Instead, you can configure your environment using the **requirements.txt** file. I have updated the instructions in the **README.md** file. Please try again by referring to it, and if any other problems occur, please let me know again.
